language: go

go:
- 1.9
- master

node_js:
- 9.1.0

before_script:
- npm install css-minify -g
- npm install stylus -g
- go get github.com/kataras/iris

#before_install:
#- openssl aes-256-cbc -K $encrypted_335949d17217_key -iv $encrypted_335949d17217_iv
#  -in deploy_rsa.enc -out deploy_rsa -d

addons:
ssh_known_hosts:
     - node-13.rosti.cz:13664
     - 46.101.184.215:13664

before_deploy:
  - openssl aes-256-cbc -K $encrypted_335949d17217_key -iv $encrypted_335949d17217_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet -e "ssh -p 13664 -o StrictHostKeyChecking=no" $TRAVIS_BUILD_DIR app@node-13.rosti.cz:/srv/app/
  on:
    branch: master
